Bring the website back to life
shawesome/rpg-website pull request #1
Opened 2024-04-19 16:57 UTC by danielgoodwin97

No problem brother. I got you. :fist_raised:

2024-04-19 17:23 UTC, robbie-thompson requested changes
LGTFM.

2024-04-19 17:23 UTC, robbie-thompson commented on server.js
> +    if (err) throw err;
Let's not use short-hand functions.
```suggestion
    if (err) {
        throw err;
    }
```

2024-04-19 17:23 UTC, robbie-thompson commented on server.js
> +    if (err) throw err;
```suggestion
    if (err) {
        throw err;
    }
```

2024-04-19 17:23 UTC, robbie-thompson commented on server.js
> +                    data === 'E' ? 'right' : player.orientation;
```suggestion
        player.action = data ? 'walk' : 'stationary';
        player.orientation = data === 'N' ? 'up' :
            data === 'S' ? 'down' :
                data === 'W' ? 'left' :
                    data === 'E' ? 'right' : player.orientation;
                    
        switch (data) {	
            case 'N': player.orientation = 'up';    break;
            case 'S': player.orientation = 'down';  break;
            case 'W': player.orientation = 'left';  break;
            case 'E': player.orientation = 'right'; break;
            default: break; // Keep existing orientation if none of the cases match
        }
```

2024-04-19 17:25 UTC, danielgoodwin97 commented on server.js
> +    if (err) throw err;
Done.

2024-04-19 17:25 UTC, danielgoodwin97 commented on server.js
> +    if (err) throw err;
Done.

2024-04-19 17:25 UTC, danielgoodwin97 commented on server.js
> +                    data === 'E' ? 'right' : player.orientation;
Done.

2024-04-19 17:30 UTC, robbie-thompson approved these changes

2024-04-19 17:30 UTC, robbie-thompson approved these changes

2024-04-19 17:31 UTC, robbie-thompson approved these changes

2024-04-19 17:31 UTC, robbie-thompson approved these changes

2024-04-19 17:31 UTC, robbie-thompson approved these changes

2024-04-19 17:31 UTC, robbie-thompson approved these changes

2024-04-19 17:31 UTC, robbie-thompson approved these changes

2024-04-19 17:31 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:32 UTC, robbie-thompson approved these changes

2024-04-19 17:33 UTC, danielgoodwin97 commented
It's got the go ahead from @robbie-thompson

2024-04-21 20:59 UTC, martinshawruroc approved these changes

2024-04-25 09:46 UTC, merged